
UPDATE Company SET status = null WHERE id > -1;
ALTER TABLE Company MODIFY COLUMN `status` enum('ACTIVE','INACTIVE','DELETED') DEFAULT 'ACTIVE';
UPDATE Company SET status = "ACTIVE" WHERE id > -1;
ALTER TABLE Company MODIFY COLUMN `status` enum('ACTIVE','INACTIVE','DELETED') NOT NULL DEFAULT 'ACTIVE';