
-- ARTICLE

CREATE TABLE Article (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	handle VARCHAR(100),
	title VARCHAR(255) NOT NULL,
	publication_date DATE,
	status ENUM('DRAFT', 'PUBLIC') DEFAULT 'DRAFT',
	media ENUM('ALL', 'CYBERLUX', 'SECURITYMADEIN.LU') DEFAULT 'ALL'
);

CREATE TABLE ArticleVersion (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	is_main BOOLEAN NOT NULL DEFAULT FALSE,
	article_id INT NOT NULL,
	FOREIGN KEY (article_id) REFERENCES Article (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ArticleBox (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	position INT NOT NULL,
	type ENUM('PARAGRAPH', 'TITLE1', 'TITLE2', 'TITLE3', 'IMAGE') NOT NULL,
	content TEXT,
	article_version_id INT NOT NULL,
	FOREIGN KEY (article_version_id) REFERENCES ArticleVersion (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ArticleCompanyTag (
	article INT NOT NULL,
	company INT NOT NULL,
	PRIMARY KEY (article, company),
	FOREIGN KEY (article) REFERENCES Article (id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (company) REFERENCES Company (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ArticleTaxonomyTag (
	article INT NOT NULL,
	taxonomy_value INT NOT NULL,
	PRIMARY KEY (article, taxonomy_value),
	FOREIGN KEY (article) REFERENCES Article (id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (taxonomy_value) REFERENCES TaxonomyValue (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- LOG

ALTER TABLE Log ADD COLUMN sys_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- IMAGE

CREATE TABLE Image (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	thumbnail BLOB NOT NULL,
	width INT NOT NULL,
	height INT NOT NULL,
	creation_date DATE NOT NULL
);

-- ARTICLE MODIFICATION

ALTER TABLE Article ADD COLUMN abstract VARCHAR(2040) AFTER title;
ALTER TABLE Article ADD COLUMN image INT AFTER media;
ALTER TABLE Article ADD FOREIGN KEY (image) REFERENCES Image (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Article ADD COLUMN type ENUM('NEWS', 'EVENT', 'TOOL', 'SERVICE', 'RESOURCE', 'JOB OFFER') DEFAULT 'NEWS' AFTER `status`;

-- COMPANY MODIFICATION

ALTER TABLE `Company` MODIFY COLUMN type enum('ACTOR', 'PARTNER', 'OPERATOR', 'JOB PLATFORM', 'OTHER') DEFAULT NULL AFTER `website`;
ALTER TABLE `Company` ADD COLUMN image INT AFTER name;

-- ARTICLEBOX MODIFICATION

ALTER TABLE `ArticleBox` MODIFY COLUMN type enum('PARAGRAPH', 'TITLE1', 'TITLE2', 'TITLE3', 'IMAGE', 'FRAME') NOT NULL;

-- COMPANY MODIFICATION

ALTER TABLE `Article` ADD COLUMN start_date DATETIME AFTER publication_date;
ALTER TABLE `Article` ADD COLUMN end_date DATETIME AFTER start_date;