name: Build and deploy on production environment

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: cache python venv
      uses: actions/cache@v2
      with:
        path: venv
        key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: install venv
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends python3 python3-venv

    - name: install requirements
      run: |
        python3 -m venv venv
        . ./venv/bin/activate
        pip3 install -U pip setuptools
        pip3 install -r requirements.txt

    - name: show built content
      run: find .

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRODUCTION_ENV_SSH_PRIVATE_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.PRODUCTION_ENV_HOST }} >> ~/.ssh/known_hosts

    - name: rsync
      run: rsync -r --delete --exclude=.git --exclude=.gitignore --exclude=.github --exclude=config/config.py ./ boapi@${{ secrets.PRODUCTION_ENV_HOST }}:/var/www/bo-api
